DROP VIEW IF EXISTS [HSNInwardReportView];
create view IF NOT EXISTS HSNInwardReportView
AS
SELECT
   ROW_NUMBER () OVER () RowNum,
Case When Products.userDefinedBarCode ISNULL
   THEN Products.barcode 
   ELSE Products.userDefinedBarCode
   end as BARCODE,
   IFNULL(PuRCHASEORDERDETAILS.HSNCODE, '') as HSNCODE,
   (
      select
         IFNULL(DISTRIBUTORS.GSTIN, '') 
      from
         DISTRIBUTORS 
      where
         DISTRIBUTORS.PHONE = PuRCHASEORDERS.DISTRIBUTORPHONE 
   )
   as GSTIN,
   PuRCHASEORDERS.ISMEMO as ISMEMO,
   IFNULL(PuRCHASEORDERDETAILS.NAME, '') as PRODUCTNAME,
   Case
      When
         PuRCHASEORDERDETAILS.Uom = "G" 
      then
         "KG" 
      WHEN
         PuRCHASEORDERDETAILS.uom = "ML" 
      then
         "L" 
      when
         PuRCHASEORDERDETAILS.Uom is null 
      then
         "" 
      ELSE
         PuRCHASEORDERDETAILS.Uom 
   end
   as UOM, sum( 
   CASE
      WHEN
         PuRCHASEORDERDETAILS.UOM = 'G' 
         or PuRCHASEORDERDETAILS.UOM = 'ML' 
      THEN
         PuRCHASEORDERDETAILS.ReCEIVEDQUANTITY / 1000.0 
      ELSE
         PuRCHASEORDERDETAILS.ReCEIVEDQUANTITY 
   END
) as RECEIVEDQUANTITY, PurchaseOrderDetails.totalAmount / 100.0 as QT, sum( 
   CASE
      WHEN
         PuRCHASEORDERS.ISPRICEEXCLUSIVE = 0 
      THEN
(IFNULL(ROUND((pURCHASEORDERDETAILS.TOTALAMOUNT) / 100.0, 2), 0) - (IFNULL(ROUND((igstAmount) / 100.0, 2), 0) + IFNULL(ROUND((SGSTAMOUNT) / 100.0, 2), 0) + IFNULL(ROUND((CGSTAMOUNT) / 100.0, 2), 0) + IFNULL(ROUND((CESSAMOUNT) / 100.0, 2), 0) + IFNULL(ROUND((ADDITIONALCESSAMOUNT) / 100.0, 2), 0) + (PuRCHASEORDERS.TOTALAMOUNT * PuRCHASEORDERS.TOTALDISCOUNT / (PuRCHASEORDERS.NETAMOUNT + + PuRCHASEORDERS.TOTALDISCOUNT)) / 100.0)) 
      ELSE
         IFNULL(ROUND(ABS(pURCHASEORDERDETAILS.TOTALAMOUNT) / 100.0, 2), 0) - IFNULL(ROUND(ABS(pURCHASEORDERDETAILS.BILLITEMSPLITDISCOUNT) / 100.0, 2), 0) 
   END
) AS TAXABLEVALUE, sum(IFNULL(ROUND((PuRCHASEORDERDETAILS.IGSTAMOUNT) / 100.0, 2), 0)) as IGSTAMOUNT, sum(IFNULL(ROUND((PuRCHASEORDERDETAILS.CGSTAMOUNT) / 100.0, 2), 0)) as CGSTAMOUNT, sum(IFNULL(ROUND((PuRCHASEORDERDETAILS.SGSTAMOUNT) / 100.0, 2), 0)) as SGSTAMOUNT, sum(IFNULL(ROUND((PuRCHASEORDERDETAILS.CESSAMOUNT) / 100.0, 2), 0)) as CESSAMOUNT, sum(IFNULL(ROUND((PuRCHASEORDERDETAILS.ADDITIONALCESSAMOUNT) / 100.0, 2), 0)) as ADDITIONALCESSAMOUNT, PurchaseOrders.orderDate as ORDERDATE 
FROM
   PuRCHASEORDERS 
   INNER JOIN
      PuRCHASEORDERDETAILS 
      ON pURCHASEORDERS.id = pURCHASEORDERDETAILS.PONUMBER 
   join
      Products 
      on pURCHASEORDERDETAILS.productCode = Products.productCode 
WHERE
   PURCHASEORDERS.iSDELETED = 0 
   and PurchaseOrders.isReturn = 0 
GROUP BY
   PuRCHASEORDERDETAILS.createdAt, PuRCHASEORDERDETAILS.hsnCode, PurchaseOrderDetails.name, PuRCHASEORDERDETAILS.PRODUCTCODE, PuRCHASEORDERS.isMEMO 
ORDER BY
   PuRCHASEORDERDETAILS.createdAt