DROP VIEW IF EXISTS [SalesRegisterReportSummaryView];
create view IF NOT EXISTS SalesRegisterReportSummaryView
AS 
SELECT
   I.createdAt as CREATEDAT,isMemo AS   ISMEMO,
   count(DISTINCT I.id) as ID,
   count(DISTINCT CUSTOMERPHONE) as CUSTOMERPHONE,
   ROUND(SUM(IFNULL(ROUND((NETAMOUNT+deliveryCharges-ifnull(PA.discountapplied,0)) / 100.0, 2), 0))) AS TOTALINVOICEVALUE,
      IFNULL(CAST(deliveryCharges as FLOAT) / 100,0) AS TOTALDELIVERYCHARGES,
ROUND(SUM(IFNULL(ROUND((totalAmount-totalSavings) / 100.0, 2), 0)),2)-ROUND(SUM(IFNULL(ROUND(TOTALIGSTAMOUNT / 100.0, 2), 0)),2)-ROUND(SUM(IFNULL(ROUND(TOTALSGSTAMOUNT / 100.0, 2), 0)),2)-ROUND(SUM(IFNULL(ROUND(TOTALCGSTAMOUNT / 100.0, 2), 0)),2)-ROUND(SUM(IFNULL(ROUND(totalCessAmount / 100.0, 2), 0)),2)-ROUND(SUM(IFNULL(ROUND(totalAdditionalCessAmount / 100.0, 2), 0)),2) AS TOTALTAXABLEVALUE,
ROUND(SUM(IFNULL(ROUND(TOTALSGSTAMOUNT / 100.0, 2), 0)),2) AS TOTALSGST,
   ROUND(SUM(IFNULL(ROUND(TOTALCGSTAMOUNT / 100.0, 2), 0)),2) AS TOTALCGST,
   ROUND(SUM(IFNULL(ROUND(TOTALIGSTAMOUNT / 100.0, 2), 0)),2) AS TOTALIGST,
   ROUND(SUM(IFNULL(ROUND(TOTALCESSAMOUNT / 100.0, 2), 0)),2) AS TOTALCESS,
   ROUND(SUM(IFNULL(ROUND(TOTALADDITIONALCESSAMOUNT / 100.0, 2), 0)),2) AS TOTALADDITIONALCESS 
FROM
   INVOICES I left join PromotionsAppliedDetails PA on I.id=Pa.invoiceId
WHERE
   ISDELETED = 0
   GROUP by I.createdAt